version: '3.8'

services:
  backend:
    image: swagger_server
    build: .
    volumes:
      - .:/usr/src/app
  frontend:
    image: web
    build:
      context: frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    ports:
      - 8000:8000