AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless Specification template describing your function.
Resources:
  ConcordanceSES:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ""
      MemorySize: 128
      Timeout: 3
      Role: "arn:aws:iam::140607339275:role/service-role/Concordance-role-5shqjxkx"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ConcordanceSES
            Method: ANY
